import React, { useEffect, useState } from "react";
import { Card, FormField, Loader } from "../components";
const RenderCards = ({ data, title }) => {
  if (data?.length > 0) {
    return data.map((post) => <Card key={post._id} {...post} />);
  }
  return (
    <h2 className="mt-5 font-bold text-[#6449ff] text-xl uppercase">{title}</h2>
  );
};
const Home = () => {
  const [loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);
  const [searchText, setSearchText] = useState("Andre Alghifari");
  return (
    <section className="max-w-7xl mx-auto">
      <div>
        <h1 className="font-extrabold text-[#222328] text-[32px]">
          The Community Showcase
        </h1>
        <p className="mt-2 text-[#666e75] text-[16px]">
          Browse through a collection of imaginative and visually stunning
          images generated by Dall-E 2.0
        </p>
      </div>

      <div className="mt-16">
        <FormField />
      </div>
      <div className="mt-10">
        {loading ? (
          <Loader className="flex justify-center items-center" />
        ) : (
          <>
            {searchText && (
              <h2 className="font-medium text-xl text-[#666e75] mb-3">
                Showing results of{" "}
                <span className="text-[#222328] bg-orange-500 rounded-md p-2">
                  {searchText}
                </span>
              </h2>
            )}

            <div
              className="grid lg:grid-cols-4 sm:grid-cols-3 
            xs:grid-cols-2 grid-cols-1 gap-3"
            >
              {searchText ? (
                <RenderCards
                  data={[]} // temporary we fill string  
                  title="No search results found"
                />
              ) : (
                <RenderCards data={[]} title="No posts found" />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  );
};

export default Home;
